# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
  sudo apt-get -y update
  sudo apt-get -y install curl git-core python-software-properties ruby-dev libreadline-dev libpq-dev build-essential nginx libsqlite3-0 libsqlite3-dev libxml2 libxml2-dev libxslt1-dev nodejs postgresql postgresql-contrib imagemagick

  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
  echo 'eval "$(rbenv init -)"'               >> ~/.bashrc
  source ~/.bashrc

  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
  sudo -H -u ubuntu bash -i -c 'rbenv install 2.4.0'
  sudo -H -u ubuntu bash -i -c 'rbenv install 2.2.5'
  sudo -H -u ubuntu bash -i -c 'rbenv install 2.3.0'
  sudo -H -u ubuntu bash -i -c 'rbenv install 2.0.0-p648'
  sudo -H -u ubuntu bash -i -c 'rbenv rehash'
  sudo -H -u ubuntu bash -i -c 'rbenv global 2.4.0'
  sudo -H -u ubuntu bash -i -c 'gem install bundler --no-ri --no-rdoc'
  sudo -H -u ubuntu bash -i -c 'rbenv rehash'
  # sudo -u postgres createdb --locale en_US.utf8 --encoding UTF8 --template template0 development
  # echo "ALTER USER postgres WITH PASSWORD \'develop\';" | sudo -u postgres psql
SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 3001, host: 3001

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.name = 'U_arctos_volucris--RUBY'
  end

  config.vm.provision :shell, privileged: false, inline: $script
end
